# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Cron Go


on:
  workflow_dispatch:
  schedule:
    - cron: "0 6,12,18,0 * * *"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Generate
      run: go main -v ./...

    - name: Commit and push
      run: |
        git config --global user.name "bingsoo420"
        git config --global user.name "gearmoss+bingsoo@gmail.com"

        git add -A
        git commit -m "Mappings.json updated"
